cdk::basic_scanner Class Reference
Public Member Functions
virtual ~basic_scanner ()
How to destroy a scanner.
std::shared_ptr< std::istream > input_stream ()
void input_stream (std::shared_ptr< std::istream > istr)
void input_stream (std::istream &istr)
std::shared_ptr< std::ostream > output_stream ()
void output_stream (std::shared_ptr< std::ostream > ostr)
void output_stream (std::ostream &ostr)
std::shared_ptr< std::ostream > error_stream ()
void error_stream (std::shared_ptr< std::ostream > estr)
void error_stream (std::ostream &estr)
std::shared_ptr< compiler > owner ()
virtual void switch_streams ()=0
virtual int scan ()=0
virtual int lineno () const =0
virtual void error (const std::string &message) const
virtual void error (const char *const message) const
Protected Member Functions
basic_scanner (const std::string &language)
Protected Attributes
const std::string _language = ``
std::shared_ptr< compiler > _compiler = nullptr
std::shared_ptr< std::istream > _istream
std::shared_ptr< std::ostream > _ostream
std::shared_ptr< std::ostream > _estream
Friends
class basic_parser
class compiler
Detailed Description
Definition at line 13 of file basic_scanner.h.
Member Function Documentation
error() [1/2]
virtual void cdk::basic_scanner::error (const char *const message) const [inline], [virtual]
Output error message.
Definition at line 136 of file basic_scanner.h.
References lineno().
error() [2/2]
virtual void cdk::basic_scanner::error (const std::string & message) const [inline], [virtual]
Output error message.
Definition at line 129 of file basic_scanner.h.
References lineno().
lineno()
virtual int cdk::basic_scanner::lineno () const [pure virtual]
Return current source line.
Implemented in cdk::yy_scanner< LexerType > .
Referenced by error().
scan()
virtual int cdk::basic_scanner::scan () [pure virtual]
Scanning algorithm: the compiler object stores the result.
Parameters
compiler the compiler object this parser belongs to.
Returns
true if the operation is successful
Implemented in cdk::yy_scanner< LexerType > .
Member Data Documentation
_estream
std::shared_ptr<std::ostream> cdk::basic_scanner::_estream [protected]
Initial value:
= std::shared_ptr<std::ostream>(&std::cerr,
                                                                           null_deleter())
Definition at line 43 of file basic_scanner.h.
_istream
std::shared_ptr<std::istream> cdk::basic_scanner::_istream [protected]
Initial value:
= std::shared_ptr<std::istream>(&std::cin,
                                                                           null_deleter())
Definition at line 35 of file basic_scanner.h.
_ostream
std::shared_ptr<std::ostream> cdk::basic_scanner::_ostream [protected]
Initial value:
= std::shared_ptr<std::ostream>(&std::cout,
                                                                           null_deleter())
Definition at line 39 of file basic_scanner.h.
The documentation for this class was generated from the following file:
cdk/basic_scanner.h