cdk::basic_factory Class Reference
#include <basic_factory.h>
Public Member Functions
virtual ~basic_factory ()
virtual std::shared_ptr< compiler > create_compiler ()
Static Public Member Functions
static basic_factory * get_implementation (const std::string &language)
Protected Member Functions
basic_factory (const std::string &language)
virtual std::shared_ptr< basic_scanner > create_scanner ()=0
virtual std::shared_ptr< basic_parser > create_parser ()=0
Protected Attributes
const std::string _language = ``
Detailed Description
This is the main factory abstract class: it provides methods for creating the lexical analyser and the compiler itself. Instances of concrete subclasses will be created by the `main` function to provide instances of the scanner and compiler objects for a concrete language.
keys are language names
values are compiler factories
Definition at line 24 of file basic_factory.h.
Constructor & Destructor Documentation
~basic_factory()
virtual cdk::basic_factory::~basic_factory () [inline], [virtual]
The superclass destructor does not do anything. Probably, it would be a good idea to clean up the factories map.
Definition at line 51 of file basic_factory.h.
Member Function Documentation
create_compiler()
virtual std::shared_ptr< compiler> cdk::basic_factory::create_compiler () [inline], [virtual]
Create a compiler object for a given language.
Parameters
name name of the language handled by the compiler
Returns
compiler object pointer
Definition at line 77 of file basic_factory.h.
References create_parser(), and create_scanner().
create_parser()
virtual std::shared_ptr< basic_parser> cdk::basic_factory::create_parser () [protected], [pure virtual]
Create a parser object for a given language.
Parameters
name name of the input file (for debug only)
Returns
parser object pointer
See also
createCompiler
Implemented in cdk::yy_factory< LexerType > .
Referenced by create_compiler().
create_scanner()
virtual std::shared_ptr< basic_scanner> cdk::basic_factory::create_scanner () [protected], [pure virtual]
Create a scanner object for a given language.
Parameters
name name of the input file (for debug only)
Returns
scanner object pointer
See also
createCompiler
Implemented in cdk::yy_factory< LexerType > .
Referenced by create_compiler().
The documentation for this class was generated from the following file:
cdk/basic_factory.h