cdk::postfix_ix86_emitter Class Reference
#include <postfix_ix86_emitter.h>
Public Member Functions
postfix_ix86_emitter (std::shared_ptr< compiler > & compiler)
std::string mklabel (const std::string &context=``)
void BSS () override
void DATA () override
void RODATA () override
void TEXT () override
void SBYTE (char value) override
void SSHORT (short value) override
void SINT (int value) override
void SFLOAT (float value) override
void SDOUBLE (double value) override
void SSTRING (std::string value) override
void SALLOC (int value) override
void SADDR (std::string label) override
void ALIGN () override
void LABEL (std::string label) override
void EXTERN (std::string label) override
void GLOBAL (const char *label, std::string type) override
void GLOBAL (std::string label, std::string type) override
void ADDR (std::string label) override
void ADDRA (std::string label) override
void ADDRV (std::string label) override
void LOCAL (int offset) override
void LOCA (int offset) override
void LOCV (int offset) override
void LDBYTE () override
void LDSHORT () override
void LDINT () override
void LDFLOAT () override
void LDDOUBLE () override
void STBYTE () override
void STSHORT () override
void STINT () override
void STFLOAT () override
void STDOUBLE () override
void SP () override
void ALLOC () override
void DUP32 () override
void DUP64 () override
void SWAP32 () override
void SWAP64 () override
void INT (int value) override
void FLOAT (float value) override
void DOUBLE (double value) override
void NEG () override
void ADD () override
void SUB () override
void MUL () override
void DIV () override
void UDIV () override
void MOD () override
void UMOD () override
void DNEG () override
void DADD () override
void DSUB () override
void DMUL () override
void DDIV () override
void INCR (int value) override
void DECR (int value) override
void D2F () override
void F2D () override
void D2I () override
void I2D () override
void EQ () override
void NE () override
void GT () override
void GE () override
void LE () override
void LT () override
void UGT () override
void UGE () override
void ULE () override
void ULT () override
void DCMP () override
void NOT ()
void AND ()
void OR ()
void XOR ()
void ROTL () override
void ROTR () override
void SHTL () override
void SHTRU () override
void SHTRS () override
void ENTER (size_t bytes) override
void START () override
void STFVAL32 () override
void STFVAL64 () override
void LEAVE () override
void RET () override
void RETN (int bytes) override
void CALL (std::string label) override
void TRASH (int bytes) override
void LDFVAL32 () override
void LDFVAL64 () override
void JMP (std::string label) override
void LEAP () override
void BRANCH () override
void JZ (std::string label) override
void JNZ (std::string label) override
void JEQ (std::string label) override
void JNE (std::string label) override
void JGT (std::string label) override
void JGE (std::string label) override
void JLE (std::string label) override
void JLT (std::string label) override
void JUGT (std::string label) override
void JUGE (std::string label) override
void JULE (std::string label) override
void JULT (std::string label) override
void NIL () override
void NOP () override
Additional Inherited Members
Detailed Description
Class postfix_ix86_emitter: emitter for yasm/nasm code.
Definition at line 13 of file postfix_ix86_emitter.h.
Member Function Documentation
ADD()
void cdk::postfix_ix86_emitter::ADD () [inline], [override], [virtual]
Arithmetic instruction: integer sum of two integer values.
Implements cdk::basic_postfix_emitter .
Definition at line 469 of file postfix_ix86_emitter.h.
ADDR()
void cdk::postfix_ix86_emitter::ADDR (std::string label) [inline], [override], [virtual]
Absolute addressing instruction: puts the address of the name passed as argument at the top of the stack.
Absolute addressing ADDR) is performed using labels. Relative addressing (LOCAL) requires a frame pointer to work: the frame pointer defines an addressing reference.
Parameters
label is the name of the memory position.
See also
LOCAL
Implements cdk::basic_postfix_emitter .
Definition at line 301 of file postfix_ix86_emitter.h.
Referenced by DOUBLE().
ADDRA()
void cdk::postfix_ix86_emitter::ADDRA (std::string label) [inline], [override], [virtual]
Absolute addressing instruction: quick opcode: the same as the sequence ADDR(name); STINT();
Parameters
label is the name of the memory position.
Implements cdk::basic_postfix_emitter .
Definition at line 305 of file postfix_ix86_emitter.h.
ADDRV()
void cdk::postfix_ix86_emitter::ADDRV (std::string label) [inline], [override], [virtual]
Absolute addressing instruction: quick opcode: the same as the sequence ADDR(name); LDINT();
Parameters
label is the name of the memory position.
Implements cdk::basic_postfix_emitter .
Definition at line 310 of file postfix_ix86_emitter.h.
ALIGN()
void cdk::postfix_ix86_emitter::ALIGN () [inline], [override], [virtual]
Forces the alignment of code or data.
Implements cdk::basic_postfix_emitter .
Definition at line 277 of file postfix_ix86_emitter.h.
Referenced by DOUBLE().
ALLOC()
void cdk::postfix_ix86_emitter::ALLOC () [inline], [override], [virtual]
Allocates in the stack as many bytes as indicated by the value at the top of the stack.
Dynamic memory allocation in the stack, equivalent to a call to the C language alloca function, changes the offsets of temporary variables that may exist in the stack when the allocation is performed. Thus, it should only be used when no temporary variables exist, or when the full import of its actions is fully understood.
Implements cdk::basic_postfix_emitter .
Definition at line 407 of file postfix_ix86_emitter.h.
AND()
void cdk::postfix_ix86_emitter::AND () [inline], [virtual]
Logical instructions: logical (bitwise) AND operation.
Implements cdk::basic_postfix_emitter .
Definition at line 713 of file postfix_ix86_emitter.h.
BSS()
void cdk::postfix_ix86_emitter::BSS () [inline], [override], [virtual]
Starts the data segment for uninitialized values.
Implements cdk::basic_postfix_emitter .
Definition at line 207 of file postfix_ix86_emitter.h.
CALL()
void cdk::postfix_ix86_emitter::CALL (std::string label) [inline], [override], [virtual]
Calls the named function. Stores the return address in the stack.
Parameters
label is the called function's name.
Implements cdk::basic_postfix_emitter .
Definition at line 807 of file postfix_ix86_emitter.h.
D2F()
void cdk::postfix_ix86_emitter::D2F () [inline], [override], [virtual]
Type conversion instructions: converts from double precision floating point to simple precision floating point.
Implements cdk::basic_postfix_emitter .
Definition at line 582 of file postfix_ix86_emitter.h.
Referenced by FLOAT().
D2I()
void cdk::postfix_ix86_emitter::D2I () [inline], [override], [virtual]
Type conversion instructions: converts from double precision floating point to integer.
Implements cdk::basic_postfix_emitter .
Definition at line 594 of file postfix_ix86_emitter.h.
DADD()
void cdk::postfix_ix86_emitter::DADD () [inline], [override], [virtual]
Arithmetic instruction: floating point sum of two double values.
Implements cdk::basic_postfix_emitter .
Definition at line 528 of file postfix_ix86_emitter.h.
DATA()
void cdk::postfix_ix86_emitter::DATA () [inline], [override], [virtual]
Starts the data segment for initialized values.
Implements cdk::basic_postfix_emitter .
Definition at line 211 of file postfix_ix86_emitter.h.
DCMP()
void cdk::postfix_ix86_emitter::DCMP () [inline], [override], [virtual]
Compares two double precision floating point values. The result is an integer value: less than 0, if the d1 is less than d2; 0, if they are equal; greater than 0, otherwise.
Implements cdk::basic_postfix_emitter .
Definition at line 694 of file postfix_ix86_emitter.h.
DDIV()
void cdk::postfix_ix86_emitter::DDIV () [inline], [override], [virtual]
Arithmetic instruction: floating point division of two double values.
Implements cdk::basic_postfix_emitter .
Definition at line 552 of file postfix_ix86_emitter.h.
DECR()
void cdk::postfix_ix86_emitter::DECR (int value) [inline], [override], [virtual]
Subtracts value from the value at the position defined by the address at the top of the stack, i.e. [a] becomes [a]-value.
Parameters
value is the value to be subtracted.
Implements cdk::basic_postfix_emitter .
Definition at line 571 of file postfix_ix86_emitter.h.
References DUP32().
DIV()
void cdk::postfix_ix86_emitter::DIV () [inline], [override], [virtual]
Arithmetic instruction: integer division of two integer values.
Implements cdk::basic_postfix_emitter .
Definition at line 485 of file postfix_ix86_emitter.h.
DMUL()
void cdk::postfix_ix86_emitter::DMUL () [inline], [override], [virtual]
Arithmetic instruction: floating point multiplication of two double values.
Implements cdk::basic_postfix_emitter .
Definition at line 544 of file postfix_ix86_emitter.h.
DNEG()
void cdk::postfix_ix86_emitter::DNEG () [inline], [override], [virtual]
Arithmetic instruction: floating point negation of double value (symmetric).
Implements cdk::basic_postfix_emitter .
Definition at line 522 of file postfix_ix86_emitter.h.
DOUBLE()
void cdk::postfix_ix86_emitter::DOUBLE (double value) [inline], [override], [virtual]
Pushes a double precision floating point value to the stack top.
Parameters
value is the value to be put in the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 449 of file postfix_ix86_emitter.h.
References ADDR(), ALIGN(), LABEL(), LDDOUBLE(), RODATA(), SDOUBLE(), and TEXT().
Referenced by FLOAT().
DSUB()
void cdk::postfix_ix86_emitter::DSUB () [inline], [override], [virtual]
Arithmetic instruction: floating point subtraction of two double values.
Implements cdk::basic_postfix_emitter .
Definition at line 536 of file postfix_ix86_emitter.h.
DUP32()
void cdk::postfix_ix86_emitter::DUP32 () [inline], [override], [virtual]
Duplicates the value at the top of the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 412 of file postfix_ix86_emitter.h.
Referenced by DECR(), and INCR().
DUP64()
void cdk::postfix_ix86_emitter::DUP64 () [inline], [override], [virtual]
Duplicates the double precision value at the top of the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 416 of file postfix_ix86_emitter.h.
References LDDOUBLE(), and SP().
ENTER()
void cdk::postfix_ix86_emitter::ENTER (size_t bytes) [inline], [override], [virtual]
Function definition instructions: starts a function: push the frame pointer (activation register) to the stack and allocate space for local variables, according to the size given as argument (in bytes).
Parameters
bytes is the space to be allocated for local variables.
Implements cdk::basic_postfix_emitter .
Definition at line 763 of file postfix_ix86_emitter.h.
EQ()
void cdk::postfix_ix86_emitter::EQ () [inline], [override], [virtual]
Integer comparison instructions: equal to.
Implements cdk::basic_postfix_emitter .
Definition at line 611 of file postfix_ix86_emitter.h.
EXTERN()
void cdk::postfix_ix86_emitter::EXTERN (std::string label) [inline], [override], [virtual]
Declares the symbol whose name is passed as argument as being externally defined, i.e., defined in another compilation module.
Parameters
label is the symbol's name.
Implements cdk::basic_postfix_emitter .
Definition at line 285 of file postfix_ix86_emitter.h.
F2D()
void cdk::postfix_ix86_emitter::F2D () [inline], [override], [virtual]
Type conversion instructions: converts from simple precision floating point to double precision floating point.
Implements cdk::basic_postfix_emitter .
Definition at line 588 of file postfix_ix86_emitter.h.
FLOAT()
void cdk::postfix_ix86_emitter::FLOAT (float value) [inline], [override], [virtual]
Pushes a single precision floating point value to the stack top.
Parameters
value is the value to be put in the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 444 of file postfix_ix86_emitter.h.
References D2F(), and DOUBLE().
GE()
void cdk::postfix_ix86_emitter::GE () [inline], [override], [virtual]
Integer comparison instructions: greater than or equal to.
Implements cdk::basic_postfix_emitter .
Definition at line 636 of file postfix_ix86_emitter.h.
GLOBAL() [1/2]
void cdk::postfix_ix86_emitter::GLOBAL (const char * label, std::string type) [inline], [override], [virtual]
Declare a name/label (first argument) with a given type (second argument; see below). Declaration of a name must preceed its definition.
Parameters
label is the name to be defined.
type is the named object's type.
See also
FUNC OBJ NONE
Implements cdk::basic_postfix_emitter .
Definition at line 289 of file postfix_ix86_emitter.h.
GLOBAL() [2/2]
void cdk::postfix_ix86_emitter::GLOBAL (std::string label, std::string type) [inline], [override], [virtual]
Declare a name/label (first argument) with a given type (second argument; see below). Declaration of a name must preceed its definition. This is the C++-friendly interface.
Parameters
label is the name to be defined.
type is the named object's type.
See also
FUNC OBJ NONE
Implements cdk::basic_postfix_emitter .
Definition at line 292 of file postfix_ix86_emitter.h.
GT()
void cdk::postfix_ix86_emitter::GT () [inline], [override], [virtual]
Integer comparison instructions: greater than.
Implements cdk::basic_postfix_emitter .
Definition at line 628 of file postfix_ix86_emitter.h.
I2D()
void cdk::postfix_ix86_emitter::I2D () [inline], [override], [virtual]
Type conversion instructions: converts from integer to double precision floating point.
Implements cdk::basic_postfix_emitter .
Definition at line 600 of file postfix_ix86_emitter.h.
INCR()
void cdk::postfix_ix86_emitter::INCR (int value) [inline], [override], [virtual]
Adds value to the value at the position defined by the address at the top of the stack, i.e. [a] becomes [a]+value.
Parameters
value is the value to be added.
Implements cdk::basic_postfix_emitter .
Definition at line 565 of file postfix_ix86_emitter.h.
References DUP32().
INT()
void cdk::postfix_ix86_emitter::INT (int value) [inline], [override], [virtual]
Pushes a integer value to the stack top.
Parameters
value is the value to be put in the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 440 of file postfix_ix86_emitter.h.
LABEL()
void cdk::postfix_ix86_emitter::LABEL (std::string label) [inline], [override], [virtual]
Generates a new label, as indicated by the argument.
Parameters
label is the new label's name.
Implements cdk::basic_postfix_emitter .
Definition at line 281 of file postfix_ix86_emitter.h.
Referenced by DOUBLE().
LDBYTE()
void cdk::postfix_ix86_emitter::LDBYTE () [inline], [override], [virtual]
Load instruction: loads 1 byte (char).
Implements cdk::basic_postfix_emitter .
Definition at line 333 of file postfix_ix86_emitter.h.
LDDOUBLE()
void cdk::postfix_ix86_emitter::LDDOUBLE () [inline], [override], [virtual]
Load instruction: loads a double precision floating point value.
Implements cdk::basic_postfix_emitter .
Definition at line 355 of file postfix_ix86_emitter.h.
Referenced by DOUBLE(), and DUP64().
LDFLOAT()
void cdk::postfix_ix86_emitter::LDFLOAT () [inline], [override], [virtual]
Load instruction: loads a single precision floating point value.
Implements cdk::basic_postfix_emitter .
Definition at line 350 of file postfix_ix86_emitter.h.
LDFVAL32()
void cdk::postfix_ix86_emitter::LDFVAL32 () [inline], [override], [virtual]
Function definition instructions: pushes the value in the accumulator register to the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 817 of file postfix_ix86_emitter.h.
LDFVAL64()
void cdk::postfix_ix86_emitter::LDFVAL64 () [inline], [override], [virtual]
Function definition instructions: pushes the value in the double precision floating point register to the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 821 of file postfix_ix86_emitter.h.
LDINT()
void cdk::postfix_ix86_emitter::LDINT () [inline], [override], [virtual]
Load instruction: loads 4 bytes (integer -- rvalue).
Implements cdk::basic_postfix_emitter .
Definition at line 345 of file postfix_ix86_emitter.h.
LDSHORT()
void cdk::postfix_ix86_emitter::LDSHORT () [inline], [override], [virtual]
Load instruction: loads 2 bytes (short).
Implements cdk::basic_postfix_emitter .
Definition at line 339 of file postfix_ix86_emitter.h.
LE()
void cdk::postfix_ix86_emitter::LE () [inline], [override], [virtual]
Integer comparison instructions: less than or equal to.
Implements cdk::basic_postfix_emitter .
Definition at line 644 of file postfix_ix86_emitter.h.
LEAVE()
void cdk::postfix_ix86_emitter::LEAVE () [inline], [override], [virtual]
Function definition instructions: ends a function: restores the frame pointer (activation register) and destroys the function-local stack data.
Implements cdk::basic_postfix_emitter .
Definition at line 789 of file postfix_ix86_emitter.h.
LOCA()
void cdk::postfix_ix86_emitter::LOCA (int offset) [inline], [override], [virtual]
Relative addressing instruction: quick opcode: the same as the sequence LOCAL(offset); STINT();
Parameters
offset from the top of the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 319 of file postfix_ix86_emitter.h.
LOCAL()
void cdk::postfix_ix86_emitter::LOCAL (int offset) [inline], [override], [virtual]
Relative addressing instruction: puts at the top of the stack the address of the local variable, obtained by computing the offset relative to the frame pointer.
The value passed as argument is as follows: greater of equal to 8, means function arguments; equal to 4, means the function's return address; equal to 0, means the frame pointer itself; less that -4, means local variables.
Parameters
offset from the top of the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 314 of file postfix_ix86_emitter.h.
LOCV()
void cdk::postfix_ix86_emitter::LOCV (int offset) [inline], [override], [virtual]
Relative addressing instruction: quick opcode: the same as the sequence ADDR(name); LDINT();
Parameters
offset from the top of the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 324 of file postfix_ix86_emitter.h.
LT()
void cdk::postfix_ix86_emitter::LT () [inline], [override], [virtual]
Integer comparison instructions: less than.
Implements cdk::basic_postfix_emitter .
Definition at line 652 of file postfix_ix86_emitter.h.
MOD()
void cdk::postfix_ix86_emitter::MOD () [inline], [override], [virtual]
Arithmetic instruction: remainder of integer division of two integer values.
Implements cdk::basic_postfix_emitter .
Definition at line 501 of file postfix_ix86_emitter.h.
MUL()
void cdk::postfix_ix86_emitter::MUL () [inline], [override], [virtual]
Arithmetic instruction: integer multiplication of two integer values.
Implements cdk::basic_postfix_emitter .
Definition at line 479 of file postfix_ix86_emitter.h.
NE()
void cdk::postfix_ix86_emitter::NE () [inline], [override], [virtual]
Integer comparison instructions: not equal to.
Implements cdk::basic_postfix_emitter .
Definition at line 619 of file postfix_ix86_emitter.h.
NEG()
void cdk::postfix_ix86_emitter::NEG () [inline], [override], [virtual]
Arithmetic instruction: negation (symmetric) of integer value.
Implements cdk::basic_postfix_emitter .
Definition at line 465 of file postfix_ix86_emitter.h.
NOT()
void cdk::postfix_ix86_emitter::NOT () [inline], [virtual]
Logical instructions: logical negation (bitwise), i.e., one's complement.
Implements cdk::basic_postfix_emitter .
Definition at line 709 of file postfix_ix86_emitter.h.
OR()
void cdk::postfix_ix86_emitter::OR () [inline], [virtual]
Logical instructions: logical (bitwise) OR operation.
Implements cdk::basic_postfix_emitter .
Definition at line 718 of file postfix_ix86_emitter.h.
RET()
void cdk::postfix_ix86_emitter::RET () [inline], [override], [virtual]
Function definition instructions: returns from a function (the stack should contain the return address).
Implements cdk::basic_postfix_emitter .
Definition at line 794 of file postfix_ix86_emitter.h.
RETN()
void cdk::postfix_ix86_emitter::RETN (int bytes) [inline], [override], [virtual]
Function definition instructions: returns from a function, but removes n bytes from the stack after removing the return address. More or less the same as RET() followed by TRASH(n).
Parameters
bytes the number of bytes to take from the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 798 of file postfix_ix86_emitter.h.
RODATA()
void cdk::postfix_ix86_emitter::RODATA () [inline], [override], [virtual]
Starts the data segment for initialized constant values.
Implements cdk::basic_postfix_emitter .
Definition at line 215 of file postfix_ix86_emitter.h.
Referenced by DOUBLE().
ROTL()
void cdk::postfix_ix86_emitter::ROTL () [inline], [override], [virtual]
Rotation and shift instructions: left rotation of stack top.
Implements cdk::basic_postfix_emitter .
Definition at line 733 of file postfix_ix86_emitter.h.
ROTR()
void cdk::postfix_ix86_emitter::ROTR () [inline], [override], [virtual]
Rotation and shift instructions: right rotation of stack top.
Implements cdk::basic_postfix_emitter .
Definition at line 738 of file postfix_ix86_emitter.h.
SADDR()
void cdk::postfix_ix86_emitter::SADDR (std::string label) [inline], [override], [virtual]
Declares a name for an address.
Parameters
label is the name to be declared.
Implements cdk::basic_postfix_emitter .
Definition at line 268 of file postfix_ix86_emitter.h.
SALLOC()
void cdk::postfix_ix86_emitter::SALLOC (int value) [inline], [override], [virtual]
Declares an uninitialized vector with the length (in bytes) given as argument.
Parameters
value is the vector's length.
Implements cdk::basic_postfix_emitter .
Definition at line 264 of file postfix_ix86_emitter.h.
SBYTE()
void cdk::postfix_ix86_emitter::SBYTE (char value) [inline], [override], [virtual]
Declares a static byte.
Parameters
value is the byte to be declared.
Implements cdk::basic_postfix_emitter .
Definition at line 228 of file postfix_ix86_emitter.h.
SDOUBLE()
void cdk::postfix_ix86_emitter::SDOUBLE (double value) [inline], [override], [virtual]
Declares a static double precision floating point value.
Parameters
value is the number to be declared.
Implements cdk::basic_postfix_emitter .
Definition at line 244 of file postfix_ix86_emitter.h.
Referenced by DOUBLE().
SFLOAT()
void cdk::postfix_ix86_emitter::SFLOAT (float value) [inline], [override], [virtual]
Declares a static simple precision floating point value.
Parameters
value is the number to be declared.
Implements cdk::basic_postfix_emitter .
Definition at line 240 of file postfix_ix86_emitter.h.
SHTL()
void cdk::postfix_ix86_emitter::SHTL () [inline], [override], [virtual]
Rotation and shift instructions: left shift of stack top.
Implements cdk::basic_postfix_emitter .
Definition at line 743 of file postfix_ix86_emitter.h.
SHTRS()
void cdk::postfix_ix86_emitter::SHTRS () [inline], [override], [virtual]
Rotation and shift instructions: right shift of stack top (signed).
Implements cdk::basic_postfix_emitter .
Definition at line 753 of file postfix_ix86_emitter.h.
SHTRU()
void cdk::postfix_ix86_emitter::SHTRU () [inline], [override], [virtual]
Rotation and shift instructions: right shift of stack top (unsigned).
Implements cdk::basic_postfix_emitter .
Definition at line 748 of file postfix_ix86_emitter.h.
SINT()
void cdk::postfix_ix86_emitter::SINT (int value) [inline], [override], [virtual]
Declares a static integer value.
Parameters
value is the number to be declared.
Implements cdk::basic_postfix_emitter .
Definition at line 236 of file postfix_ix86_emitter.h.
SP()
void cdk::postfix_ix86_emitter::SP () [inline], [override], [virtual]
Pushes to the stack the value of the stack pointer.
Implements cdk::basic_postfix_emitter .
Definition at line 403 of file postfix_ix86_emitter.h.
Referenced by DUP64().
SSHORT()
void cdk::postfix_ix86_emitter::SSHORT (short value) [inline], [override], [virtual]
Declares a static word.
Parameters
value is the word to be declared.
Implements cdk::basic_postfix_emitter .
Definition at line 232 of file postfix_ix86_emitter.h.
SSTRING()
void cdk::postfix_ix86_emitter::SSTRING (std::string value) [inline], [override], [virtual]
Declares a static character string (no special characters are allowed in value).
Parameters
value is the string to be declared.
Implements cdk::basic_postfix_emitter .
Definition at line 248 of file postfix_ix86_emitter.h.
START()
void cdk::postfix_ix86_emitter::START () [inline], [override], [virtual]
Function definition instructions: equivalent to ENTER(0).
Implements cdk::basic_postfix_emitter .
Definition at line 769 of file postfix_ix86_emitter.h.
STBYTE()
void cdk::postfix_ix86_emitter::STBYTE () [inline], [override], [virtual]
Store instruction: stores 1 byte (char).
Implements cdk::basic_postfix_emitter .
Definition at line 366 of file postfix_ix86_emitter.h.
STDOUBLE()
void cdk::postfix_ix86_emitter::STDOUBLE () [inline], [override], [virtual]
Store instruction: stores a double precision floating point value.
Implements cdk::basic_postfix_emitter .
Definition at line 390 of file postfix_ix86_emitter.h.
STFLOAT()
void cdk::postfix_ix86_emitter::STFLOAT () [inline], [override], [virtual]
Store instruction: stores a single precision floating point value.
Implements cdk::basic_postfix_emitter .
Definition at line 384 of file postfix_ix86_emitter.h.
STFVAL32()
void cdk::postfix_ix86_emitter::STFVAL32 () [inline], [override], [virtual]
Function definition instructions: removes a value from the stack (to the accumulator register).
Implements cdk::basic_postfix_emitter .
Definition at line 779 of file postfix_ix86_emitter.h.
STFVAL64()
void cdk::postfix_ix86_emitter::STFVAL64 () [inline], [override], [virtual]
Function definition instructions: removes a double precision floating point value from the stack (to a double prevision floating point register).
Implements cdk::basic_postfix_emitter .
Definition at line 783 of file postfix_ix86_emitter.h.
STINT()
void cdk::postfix_ix86_emitter::STINT () [inline], [override], [virtual]
Store instruction: stores 4 bytes (integer).
Implements cdk::basic_postfix_emitter .
Definition at line 378 of file postfix_ix86_emitter.h.
STSHORT()
void cdk::postfix_ix86_emitter::STSHORT () [inline], [override], [virtual]
Store instruction: stores 2 bytes (short).
Implements cdk::basic_postfix_emitter .
Definition at line 372 of file postfix_ix86_emitter.h.
SUB()
void cdk::postfix_ix86_emitter::SUB () [inline], [override], [virtual]
Arithmetic instruction: integer subtraction of two integer values.
Implements cdk::basic_postfix_emitter .
Definition at line 474 of file postfix_ix86_emitter.h.
SWAP32()
void cdk::postfix_ix86_emitter::SWAP32 () [inline], [override], [virtual]
Exchanges the two elements at the top of the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 422 of file postfix_ix86_emitter.h.
SWAP64()
void cdk::postfix_ix86_emitter::SWAP64 () [inline], [override], [virtual]
Exchanges the two elements at the top of the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 429 of file postfix_ix86_emitter.h.
TEXT()
void cdk::postfix_ix86_emitter::TEXT () [inline], [override], [virtual]
Starts the text (code) segment.
Implements cdk::basic_postfix_emitter .
Definition at line 219 of file postfix_ix86_emitter.h.
Referenced by DOUBLE().
TRASH()
void cdk::postfix_ix86_emitter::TRASH (int bytes) [inline], [override], [virtual]
Function definition instructions: removes n bytes from the stack.
Parameters
bytes the number of bytes to take from the stack.
Implements cdk::basic_postfix_emitter .
Definition at line 812 of file postfix_ix86_emitter.h.
UDIV()
void cdk::postfix_ix86_emitter::UDIV () [inline], [override], [virtual]
Arithmetic instruction: integer division of two natural (integer) values.
Implements cdk::basic_postfix_emitter .
Definition at line 493 of file postfix_ix86_emitter.h.
UGE()
void cdk::postfix_ix86_emitter::UGE () [inline], [override], [virtual]
Integer comparison instructions: greater than or equal to for natural numbers (unsigned integers).
Implements cdk::basic_postfix_emitter .
Definition at line 669 of file postfix_ix86_emitter.h.
UGT()
void cdk::postfix_ix86_emitter::UGT () [inline], [override], [virtual]
Integer comparison instructions: greater than for natural numbers (unsigned integers).
Implements cdk::basic_postfix_emitter .
Definition at line 661 of file postfix_ix86_emitter.h.
ULE()
void cdk::postfix_ix86_emitter::ULE () [inline], [override], [virtual]
Integer comparison instructions: less than or equal to for natural numbers (unsigned integers).
Implements cdk::basic_postfix_emitter .
Definition at line 677 of file postfix_ix86_emitter.h.
ULT()
void cdk::postfix_ix86_emitter::ULT () [inline], [override], [virtual]
Integer comparison instructions: less than for natural numbers (unsigned integers).
Implements cdk::basic_postfix_emitter .
Definition at line 685 of file postfix_ix86_emitter.h.
UMOD()
void cdk::postfix_ix86_emitter::UMOD () [inline], [override], [virtual]
Arithmetic instruction: remainder of integer division of two natural (integer) values.
Implements cdk::basic_postfix_emitter .
Definition at line 509 of file postfix_ix86_emitter.h.
XOR()
void cdk::postfix_ix86_emitter::XOR () [inline], [virtual]
Logical instructions: logical (bitwise) XOR operation.
Implements cdk::basic_postfix_emitter .
Definition at line 723 of file postfix_ix86_emitter.h.
The documentation for this class was generated from the following file:
cdk/emitters/postfix_ix86_emitter.h